BOOKS = [
    {
        "title": "Anaximander",
        "author": "Carlo Rovelli",
        "completed_date": "2026-04-01",
        "rating": 4,
    },
    {
        "title": "Inference Engineering",
        "author": "Philip Kiely",
        "completed_date": "2026-01-04",
        "rating": 4,
    },
    {
        "title": "Empire of AI",
        "author": "Karen Hao",
        "completed_date": "2026-01-03",
        "rating": 2,
    },
    {
        "title": "LLMOps",
        "author": "Abi Aryan",
        "completed_date": "2026-01-02",
        "rating": 2,
    },
    {
        "title": "Old Man's War",
        "author": "John Scalzi",
        "completed_date": "2026-01-01",
        "rating": 3,
    },
    {
        "title": "The Ultra-Scale Playbook",
        "author": "Hugging Face Team",
        "completed_date": "2025-01-15",
        "rating": 4,
    },
    {
        "title": "Machine Learning System Design",
        "author": "Valerii Babushkin and Arseny Kravchenko",
        "completed_date": "2025-01-14",
        "rating": 3,
    },
    {
        "title": "Software Engineering after the Vibe Shift",
        "author": "Sean Goedecke",
        "completed_date": "2025-01-13",
        "rating": 3,
    },
    {
        "title": "On Writing Well",
        "author": "William Zinsser",
        "completed_date": "2025-01-12",
        "rating": 4,
    },
    {
        "title": "LLMs in Production",
        "author": "Christopher Brousseau",
        "completed_date": "2025-01-11",
        "rating": 5,
    },
    {
        "title": "The Sovereign Child",
        "author": "Aaron Stupple",
        "completed_date": "2025-01-10",
        "rating": 3,
    },
    {
        "title": "Expecting Better",
        "author": "Emily Oster",
        "completed_date": "2025-01-09",
        "rating": 3,
    },
    {
        "title": "Reinforcement Learning from Human Feedback",
        "author": "Nathan Lambert",
        "completed_date": "2025-01-08",
        "rating": 3,
    },
    {
        "title": "We're Pregnant!",
        "author": "Adrian Kulp",
        "completed_date": "2025-01-07",
        "rating": 3,
    },
    {
        "title": "The Almanack of Naval Ravikant",
        "author": "Eric Jorgenson",
        "completed_date": "2025-01-06",
        "rating": 4,
    },
    {
        "title": "AI Engineering",
        "author": "Chip Huyen",
        "completed_date": "2025-01-05",
        "rating": 5,
    },
    {
        "title": "Self-Help Is Like a Vaccine",
        "author": "Bryan Caplan",
        "completed_date": "2025-01-04",
        "rating": 2,
    },
    {
        "title": "Food Rules",
        "author": "Michael Pollan",
        "completed_date": "2025-01-03",
        "rating": 1,
    },
    {
        "title": "Hypermedia Systems",
        "author": "Carson Gross",
        "completed_date": "2025-01-02",
        "rating": 2,
    },
    {
        "title": "Four Thousand Weeks",
        "author": "Oliver Burkeman",
        "completed_date": "2025-01-01",
        "rating": 4,
    },
    {
        "title": "LLM Engineer's Handbook",
        "author": "Maxime Labonne and Paul Iusztin",
        "completed_date": "2024-01-12",
        "rating": 5,
    },
    {
        "title": "The Secrets of Consulting",
        "author": "Gerald Weinberg",
        "completed_date": "2024-01-11",
        "rating": 3,
    },
    {
        "title": "Build a Large Language Model (From Scratch)",
        "author": "Sebastian Raschka",
        "completed_date": "2024-01-10",
        "rating": 5,
    },
    {
        "title": "The Making of Prince of Persia",
        "author": "Jordan Mechner",
        "completed_date": "2024-01-09",
        "rating": 5,
    },
    {
        "title": "Wild Problems",
        "author": "Russ Roberts",
        "completed_date": "2024-01-08",
        "rating": 3,
    },
    {
        "title": "Light Bringer",
        "author": "Pierce Brown",
        "completed_date": "2024-01-07",
        "rating": 4,
    },
    {
        "title": "Designing Data-Intensive Applications",
        "author": "Martin Kleppmann",
        "completed_date": "2024-01-06",
        "rating": 4,
    },
    {
        "title": "Same as Ever",
        "author": "Morgan Housel",
        "completed_date": "2024-01-05",
        "rating": 5,
    },
    {
        "title": "Simple Truths",
        "author": "Kent Nerburn",
        "completed_date": "2024-01-04",
        "rating": 3,
    },
    {
        "title": "Neural Network Methods for Natural Language Processing",
        "author": "Yoav Goldberg",
        "completed_date": "2024-01-03",
        "rating": 4,
    },
    {
        "title": "Deep Learning from Scratch",
        "author": "Seth Weidman",
        "completed_date": "2024-01-02",
        "rating": 3,
    },
    {
        "title": "The Staff Engineer's Path",
        "author": "Tanya Reilly",
        "completed_date": "2024-01-01",
        "rating": 3,
    },
    {
        "title": "How to Lie with Statistics",
        "author": "Darrell Huff",
        "completed_date": "2023-01-12",
        "rating": 5,
    },
    {
        "title": "A Philosophy of Software Design",
        "author": "John Ousterhout",
        "completed_date": "2023-01-11",
        "rating": 4,
    },
    {
        "title": "Ego Is the Enemy",
        "author": "Ryan Holiday",
        "completed_date": "2023-01-10",
        "rating": 4,
    },
    {
        "title": "She Comes First",
        "author": "Ian Kerner",
        "completed_date": "2023-01-09",
        "rating": 2,
    },
    {
        "title": "Machine Learning Q and AI",
        "author": "Sebastian Raschka",
        "completed_date": "2023-01-08",
        "rating": 5,
    },
    {
        "title": "How to Avoid a Climate Disaster",
        "author": "Bill Gates",
        "completed_date": "2023-01-07",
        "rating": 1,
    },
    {
        "title": "Effective Python",
        "author": "Brett Slatkin",
        "completed_date": "2023-01-06",
        "rating": 3,
    },
    {
        "title": "What I Talk About When I Talk About Running",
        "author": "Haruki Murakami",
        "completed_date": "2023-01-05",
        "rating": 5,
    },
    {
        "title": "Sea of Tranquility",
        "author": "Emily St. John Mandel",
        "completed_date": "2023-01-04",
        "rating": 5,
    },
    {
        "title": "Machine Learning Design Patterns",
        "author": "Valliappa Lakshmanan, Sara Robinson, and Michael Munn",
        "completed_date": "2023-01-03",
        "rating": 4,
    },
    {
        "title": "Just Keep Buying",
        "author": "Nick Maggiulli",
        "completed_date": "2023-01-02",
        "rating": 3,
    },
    {
        "title": "The Practice",
        "author": "Seth Godin",
        "completed_date": "2023-01-01",
        "rating": 5,
    },
    {
        "title": "A Common-Sense Guide to Data Structures and Algorithms",
        "author": "Jay Wengrow",
        "completed_date": "2022-01-14",
        "rating": 3,
    },
    {
        "title": "Hell Yeah or No",
        "author": "Derek Sivers",
        "completed_date": "2022-01-13",
        "rating": 4,
    },
    {
        "title": "Designing Machine Learning Systems",
        "author": "Chip Huyen",
        "completed_date": "2022-01-12",
        "rating": 5,
    },
    {
        "title": "Die with Zero",
        "author": "Bill Perkins",
        "completed_date": "2022-01-11",
        "rating": 3,
    },
    {
        "title": "Mating in Captivity",
        "author": "Esther Perel",
        "completed_date": "2022-01-10",
        "rating": 2,
    },
    {
        "title": "Couples That Work",
        "author": "Jennifer Petriglieri",
        "completed_date": "2022-01-09",
        "rating": 3,
    },
    {
        "title": "Architecture Patterns with Python",
        "author": "Bob Gregory and Harry Percival",
        "completed_date": "2022-01-08",
        "rating": 2,
    },
    {
        "title": "Building Machine Learning Applications",
        "author": "Emmanuel Ameisen",
        "completed_date": "2022-01-07",
        "rating": 4,
    },
    {
        "title": "Run Like a Pro",
        "author": "Matt Fitzgerald",
        "completed_date": "2022-01-06",
        "rating": 2,
    },
    {
        "title": "So Good They Can't Ignore You",
        "author": "Cal Newport",
        "completed_date": "2022-01-05",
        "rating": 3,
    },
    {
        "title": "Think Again",
        "author": "Adam Grant",
        "completed_date": "2022-01-04",
        "rating": 4,
    },
    {
        "title": "Meditations",
        "author": "Marcus Aurelius",
        "completed_date": "2022-01-03",
        "rating": 3,
    },
    {
        "title": "Finding Ultra",
        "author": "Rich Roll",
        "completed_date": "2022-01-02",
        "rating": 5,
    },
    {
        "title": "Sandworm",
        "author": "Andy Greenberg",
        "completed_date": "2022-01-01",
        "rating": 5,
    },
    {
        "title": "Practices of the Python Pro",
        "author": "Dane Hillard",
        "completed_date": "2021-01-05",
        "rating": 4,
    },
    {
        "title": "Start Small, Stay Small",
        "author": "Rob Walling",
        "completed_date": "2021-01-04",
        "rating": 2,
    },
    {
        "title": "A Random Walk Down Wall Street",
        "author": "Burton Malkiel",
        "completed_date": "2021-01-03",
        "rating": 3,
    },
    {
        "title": "The Hacker's Guide to Scaling Python",
        "author": "Julien Danjou",
        "completed_date": "2021-01-02",
        "rating": 4,
    },
    {
        "title": "The Pragmatic Programmer",
        "author": "Andrew Hunt",
        "completed_date": "2021-01-01",
        "rating": 4,
    },
    {
        "title": "Deep Work",
        "author": "Cal Newport",
        "completed_date": "2020-01-06",
        "rating": 5,
    },
    {
        "title": "Algorithms to Live By",
        "author": "Brian Christian and Tom Griffiths",
        "completed_date": "2020-01-05",
        "rating": 3,
    },
    {
        "title": "The 4-Hour Workweek",
        "author": "Tim Ferriss",
        "completed_date": "2020-01-04",
        "rating": 4,
    },
    {
        "title": "Drive",
        "author": "Daniel H. Pink",
        "completed_date": "2020-01-03",
        "rating": 4,
    },
    {
        "title": "Propaganda",
        "author": "Edward Bernays",
        "completed_date": "2020-01-02",
        "rating": 3,
    },
    {
        "title": "It Doesn't Have to Be Crazy at Work",
        "author": "Jason Fried",
        "completed_date": "2020-01-01",
        "rating": 3,
    },
    {
        "title": "Very Good Lives",
        "author": "J.K. Rowling",
        "completed_date": "2019-01-12",
        "rating": 2,
    },
    {
        "title": "The Hard Thing About Hard Things",
        "author": "Ben Horowitz",
        "completed_date": "2019-01-11",
        "rating": 3,
    },
    {
        "title": "High Output Management",
        "author": "Andrew S. Grove",
        "completed_date": "2019-01-10",
        "rating": 4,
    },
    {
        "title": "Dark Age",
        "author": "Pierce Brown",
        "completed_date": "2019-01-09",
        "rating": 5,
    },
    {
        "title": "Siddhartha",
        "author": "Hermann Hesse",
        "completed_date": "2019-01-08",
        "rating": 3,
    },
    {
        "title": "Everybody Lies",
        "author": "Seth Stephens-Davidowitz",
        "completed_date": "2019-01-07",
        "rating": 4,
    },
    {
        "title": "The Consuming Fire",
        "author": "John Scalzi",
        "completed_date": "2019-01-05",
        "rating": 3,
    },
    {
        "title": "The Taboo Against Knowing Who You Are",
        "author": "Alan Watts",
        "completed_date": "2019-01-04",
        "rating": 4,
    },
    {
        "title": "AI Superpowers",
        "author": "Kai-Fu Lee",
        "completed_date": "2019-01-03",
        "rating": 4,
    },
    {
        "title": "Man's Search for Meaning",
        "author": "Viktor Frankl",
        "completed_date": "2019-01-02",
        "rating": 4,
    },
    {
        "title": "The Collapsing Empire",
        "author": "John Scalzi",
        "completed_date": "2019-01-01",
        "rating": 4,
    },
    {
        "title": "The Mom Test",
        "author": "Rob Fitzpatrick",
        "completed_date": "2018-01-10",
        "rating": 5,
    },
    {
        "title": "Your Money or Your Life",
        "author": "Vicki Robin",
        "completed_date": "2018-01-09",
        "rating": 5,
    },
    {
        "title": "Chaos Monkeys",
        "author": "Antonio Garcia Martinez",
        "completed_date": "2018-01-08",
        "rating": 4,
    },
    {
        "title": "We Need to Talk",
        "author": "Celeste Headlee",
        "completed_date": "2018-01-07",
        "rating": 4,
    },
    {
        "title": "Children of Time",
        "author": "Adrian Tchaikovsky",
        "completed_date": "2018-01-06",
        "rating": 2,
    },
    {
        "title": "How to Win Friends and Influence People",
        "author": "Dale Carnegie",
        "completed_date": "2018-01-05",
        "rating": 5,
    },
    {
        "title": "Zero to One",
        "author": "Peter Thiel",
        "completed_date": "2018-01-04",
        "rating": 4,
    },
    {
        "title": "Iron Gold",
        "author": "Pierce Brown",
        "completed_date": "2018-01-03",
        "rating": 5,
    },
    {
        "title": "The Martian",
        "author": "Andy Weir",
        "completed_date": "2018-01-02",
        "rating": 4,
    },
    {
        "title": "Artemis",
        "author": "Andy Weir",
        "completed_date": "2018-01-01",
        "rating": 4,
    },
]
