server {
    listen 1111;
    server_name localhost;
    absolute_redirect off;
    port_in_redirect off;
    root /usr/share/nginx/html;
    index index.html;

    error_page 404 /404.html;

    location = / {
        try_files /index.html =404;
    }

    location = /index.html {
        return 308 /;
    }

    location ~ ^(.+)\.html$ {
        return 308 $1;
    }

    location ~ ^/(.+)/$ {
        if (-f $document_root/$1.html) {
            return 308 /$1;
        }

        try_files /$1/index.html /404.html;
    }

    location / {
        try_files $uri.html $uri $uri/ /404.html;
    }
}
